- name: dispatch the server configure
  hosts: dispatch
  become: yes
  tasks:
  - name: install golang
    ansible.builtin.yum:
     name: golang
     state: installed
  
  - name: check whether the user was exists or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true
  
  - name: print the output
    ansible.builtin.debug:
     msg: "{{output}}"
  
  - when: output.rc!=0
    name: create a roboshopuser
    ansible.builtin.user:
     name: roboshop
  
  - name: check whether the directory is existsor not
    ansible.builtin.stat:
     path: /app
    register: directory

  - name: print the directory
    ansible.builtin.debug:
     msg: "{{directory}}"
  
  - when: directory.stat.exists==false
    name: create a app directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: download the app code
    ansible.builtin.unarchive:
     src: https://roboshop-builds.s3.amazonaws.com/dispatch.zip
     dest: /app
     remote_src: yes

  - name: download the dependencies
    ansible.builtin.shell: "{{item}}"
    args:
     chdir: /app
    loop:
    - "go mod init dispatch"
    - "go get"
    - "go build"

  - name: copy the file
    ansible.builtin.copy:
     src: dispatch.service
     dest: /etc/systemd/system/dispatch.service
  
  - name: daemon_reload
    ansible.builtin.systemd:
     daemon_reload: true
  
  - name: enable & start the service
    ansible.builtin.service:
     name: dispatch
     state: started
     enabled: true