- name: configure the sql server
  hosts: mysql
  become: yes
  tasks:
  - name: disable mysql in os default 
    ansible.builtin.service:
     name: mysql
     state: stopped
     enabled: no

  - name: copy the repo file
    ansible.builtin.copy:
     src: mysql.repo
     dest: /etc/yum.repos.d/mysql.repo

  - name: install sql server 
    ansible.builtin.yum:
     name: mysql-community-server
     state: installed

  - name: enable & start the mysql service
    ansible.builtin.service:
     name: mysqld
     state: started
     enabled: true
     
  - name: change the root password 
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1