- name: install user module using playbook
  hosts: user
  become: yes
  tasks:
  - name: install the script by vendor
    ansible.builtin.shell: https://rpm.nodesource.com/setup_lts.x | bash

  - name: install nodejs
    ansible.builtin.yum:
     name: nodejs
     state: installed
  
  - name: check whether the user was exists or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true
  
  - name: print the output
    ansible.builtin.debug:
     msg: "{{output}}"
  
  - when: output.rc!=0
    name: create a roboshopuser
    ansible.builtin.user:
     name: roboshop
  
  - name: check whether the directory is existsor not
    ansible.builtin.stat:
     path: /app
    register: directory
    disable_gpg_check: true
  
  - name: print the directory
    ansible.builtin.debug:
     msg: "{{directory}}"
  
  - when: directory.stat.exists==false
    name: create a app directory
    ansible.builtin.file:
     path: /app
     state: directory
  
  - name: download the application code 
    ansible.builtin.get_url:
     url: https://roboshop-builds.s3.amazonaws.com/cart.zip
     dest: /tmp
  
  - name: unzip the application zip file
    ansible.builtin.unarchive:
     src: /tmp/cart.zip
     dest: /app
  
  - name: install the essential dependencies
    ansible.builtin.command: npm install
    args:
     chdir: /app

  - name: copy the user service file
    ansible.builtin.copy:
     src: user.service
     dest: /etc/systemd/system/user.service
  
  - name: daemon reload 
    ansible.builtin.systemd:
     daemon_reload: true
  
  - name: enable & start the user service
    ansible.builtin.service:
     name: user
     state: started
     enabled: true
  
  - name: copy the mongo repo file 
    ansible.builtin.copy:
     src: mongo.repo
     dest: /etc/yum.repos.d/mongo.repo
  
  - name: install mongodb
    ansible.builtin.yum:
     name: mongodb-org-shell
     state: installed